version: "3.5"

services:
  postgres-server:
    image: postgres:latest
    env_file:
      - ./env_vars/.env_sql
  snmp-server:
    image: zabbix/zabbix-snmptraps:latest
    ports:
      - "162:162"
    volumes:
      - ./zbx_instance/snmptraps:/var/lib/zabbix/snmptraps:rw
      - ./var/lib/zabbix/mibs:/usr/share/snmp/mibs:ro
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    ports:
      - "10051:10051"
    env_file:
      - ./env_vars/.env_zabbix
    volumes:
      - ./zbx_instance/snmptraps:/var/lib/zabbix/snmptraps:rw
      - ./var/lib/zabbix/mibs:/usr/share/snmp/mibs:ro
    depends_on:
      - postgres-server
  web-server:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    ports:
      - "80:8080"
    env_file:
      - ./env_vars/.env_web
    volumes:
      - ./etc/ssl/nginx:/etc/ssl/nginx:ro
    depends_on:
      - zabbix-server
    